on: [push, pull_request]
name: luacheck
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: lint
        uses: lunarmodules/luacheck@master
        with:
          luacheckrc_url: ""
